package plan

import (
	"crypto/sha256"
	"encoding/hex"

	"github.com/google/uuid"
)

// Planner constructs a Plan from an UncertaintyReport. This is the core
// Phase 2 PR-B1 surface; Phase 4 Verify and Phase 5 Learn consume the
// resulting Plan.
//
// Implementations:
//   - DefaultPlanner (this package): deterministic, no LLM
//   - LLMPlanner (future PR-B3 or Phase 6+): LLM-augmented decomposition
//
// The interface returns an error if any PP-1/2/3 constraint fails — the
// caller (Orchestrator) routes the error to handlePlanError and discards
// the partial Plan.
type Planner interface {
	// Plan takes the structured observation report and produces a dispatch-ready
	// Plan. The Plan has been validated against PP-1/2/3 by the time it returns
	// successfully; callers do not need to call Validate() again.
	Plan(input PlanInput) (*Plan, error)
}

// PlanInput is the minimal projection the Planner needs from upstream layers.
// Defined as a struct (not an interface) so the Plan package stays independent
// of orchtypes (no import cycle, matches Phase 1 MemoryEntry precedent).
//
// SourceObservationIDs is the subset of observation IDs that contributed to
// the Strength calculation. The full Observations slice is the source for
// ComputeOverallStrength / MatchKind / FilterByKind.
type PlanInput struct {
	SessionID            string
	ObservationIDs       []string         // IDs that drove Strength (PP-1 line)
	QuantizedKind        string           // From Phase 2 IntentQuantizer (e.g. "intent_fast")
	AnomaliesCount       int              // len(UncertaintyReport.Anomalies)
	Steps                []Step           // From LLMDecomposer (future PR-B3)
	FailureCriteria      []FailureCriterion // From Validator
	BlastRadius          BlastRadius
}

// DefaultPlanner is the deterministic, no-LLM Planner used by Phase 2 PR-B1.
//
// Future PR-B3 may add LLMPlanner; the interface allows swapping without
// changing call sites.
type DefaultPlanner struct{}

// NewDefaultPlanner constructs a DefaultPlanner.
func NewDefaultPlanner() *DefaultPlanner {
	return &DefaultPlanner{}
}

// Plan constructs a Plan from input. It:
//  1. Determines PlanKind via MatchKind(input.ObservationIDs)
//  2. Caps Strength at min(input.ObservationIDs-derived Strength floor, 1.0)
//  3. Propagates AnomaliesCount
//  4. Validates against PP-2 + PP-3
//
// If input.ObservationIDs is empty, returns ErrPlanSourceObservationIDsRequired.
// If validation fails, returns the first violation (caller discards partial Plan).
//
// The ID is generated by the caller — DefaultPlanner does not invent IDs.
func (p *DefaultPlanner) Plan(input PlanInput) (*Plan, error) {
	if len(input.ObservationIDs) == 0 {
		return nil, NewPlanSourceObservationIDsRequiredError()
	}

	kind := MatchKind(input.QuantizedKind, len(input.Steps), input.AnomaliesCount)

	// Strength derivation: cap at min(input.AnomaliesCount-derived floor, 1.0).
	// We don't have direct access to UncertaintyReport here, so use the
	// caller-provided AnomaliesCount as a proxy: more anomalies → lower floor.
	strength := strengthFloor(input.AnomaliesCount, len(input.ObservationIDs))

	steps := input.Steps
	if steps == nil {
		steps = []Step{}
	}
	fc := input.FailureCriteria
	if fc == nil {
		fc = []FailureCriterion{}
	}

	planID := NewPlanID(input.SessionID, input.ObservationIDs)
	pl := NewPlan(planID, input.SessionID, kind, input.ObservationIDs, steps, strength).
		WithFailureCriteria(fc).
		WithBlastRadius(input.BlastRadius).
		WithAnomaliesCount(input.AnomaliesCount)

	if err := pl.Validate(); err != nil {
		return nil, err
	}
	return &pl, nil
}

// MatchKind is the 4-rules classifier that maps a quantized intent + step count
// + anomalies count to a PlanKind. It is the Phase 2 PR-B1 implementation of
// doc 43 §4.5.
//
// Rules (in priority order):
//  1. If QuantizedKind == "intent_orchestrate" OR AnomaliesCount >= 3 → ExplorationPlan
//     (uncertain or high-anomaly → need parallel experiments)
//  2. If len(Steps) == 1 → CommitmentPlan
//     (single-step is almost always a direct commit)
//  3. If QuantizedKind == "intent_command" OR len(Steps) <= 3 → ProtocolPlan
//     (multi-step deterministic, tolerates partial completion)
//  4. Otherwise → ScenarioPlan
//     (read-only probe when the intent is exploratory)
//
// Tie-break (uncertainty first): when AnomaliesCount == 0 and rules don't
// clearly favor commitment, ExplorationPlan wins over ScenarioPlan to
// preserve reversibility (cheaper to roll back parallel experiments).
func MatchKind(quantizedKind string, stepCount, anomaliesCount int) PlanKind {
	// Rule 1: Uncertainty / high-anomaly → Exploration
	if quantizedKind == "intent_orchestrate" || anomaliesCount >= 3 {
		return ExplorationPlan
	}
	// Rule 2: Single step → direct commit
	if stepCount == 1 {
		return CommitmentPlan
	}
	// Rule 3: Multi-step deterministic → protocol
	if quantizedKind == "intent_command" || stepCount <= 3 {
		return ProtocolPlan
	}
	// Rule 4: Default → read-only probe
	return ScenarioPlan
}

// strengthFloor derives a [0, 1] strength from anomaly count + observation count.
// Higher anomaly count lowers the floor (more cautious execution).
//
// Formula:
//   - start at 0.7 (high confidence baseline)
//   - subtract 0.1 per anomaly (capped at 0)
//   - cap at 1.0 minimum observation guarantee (n observations → +min(n*0.02, 0.2))
func strengthFloor(anomaliesCount, observationCount int) float64 {
	floor := 0.7
	floor -= float64(anomaliesCount) * 0.1
	if floor < 0 {
		floor = 0
	}
	bonus := float64(observationCount) * 0.02
	if bonus > 0.2 {
		bonus = 0.2
	}
	floor += bonus
	if floor > 1 {
		floor = 1
	}
	return floor
}

// NewPlanID generates a stable, collision-resistant Plan ID.
//
// Format: "plan_<uuid-prefix>_<input-hash-prefix>"
//   - uuid-prefix: 8-char UUID segment (16M values per session, collision-safe)
//   - input-hash-prefix: 8-char SHA-256 hex of (sessionID + sorted obsIDs).
//     The hash makes the ID deterministic for the same input set — useful
//     for caching / re-derivation in tests and trace dedup, while the
//     UUID segment ensures different Plan invocations for the same input
//     (e.g. a Plan re-Planned after a Verify retry) get distinct IDs.
//
// The previous format ("plan_" + sessionID + "_" + obsIDs[0]) had two
// problems:
//  1. If sessionID or obsID contained '_' or ':' or '.', the format
//     became ambiguous on round-trip parsing (LogReader split on '_').
//  2. If two Plan calls in the same session used the same first obsID
//     (a legitimate occurrence, e.g. replanning after Verify retry),
//     the IDs collided — silent dedup in downstream trace queries.
func NewPlanID(sessionID string, observationIDs []string) string {
	// Sorted, deduped input set for the deterministic hash.
	uniq := make(map[string]struct{}, len(observationIDs))
	for _, id := range observationIDs {
		if id == "" {
			continue
		}
		uniq[id] = struct{}{}
	}
	ordered := make([]string, 0, len(uniq))
	for id := range uniq {
		ordered = append(ordered, id)
	}
	sortStrings(ordered)

	h := sha256.New()
	h.Write([]byte(sessionID))
	for _, id := range ordered {
		h.Write([]byte{0})
		h.Write([]byte(id))
	}
	hashHex := hex.EncodeToString(h.Sum(nil))
	return "plan_" + uuid.New().String()[:8] + "_" + hashHex[:8]
}

// sortStrings sorts a string slice in ascending order. Local helper to
// avoid importing "sort" at file scope for one call site.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}