package interfaces

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
	"time"
)

// TraceIDPrefix is prepended to every auto-generated TaskSpec.TraceID so
// downstream tooling can recognise the format ("ts_<8 hex chars>") and route
// lookups accordingly. The prefix is stable across versions.
const TraceIDPrefix = "ts_"

// traceIDEntropyBytes controls the size of the random tail. 4 bytes → 8 hex
// characters → ~4.3B unique IDs, well above the per-session volume we expect
// (tens of thousands). Larger values would inflate TraceID without buying
// meaningful extra entropy.
const traceIDEntropyBytes = 4

// Constraint is one row of TaskSpec.HardConstraints. Required=true means a
// violation short-circuits the worker; required=false downgrades it to a
// warning. Both flavors are needed — soft constraints are how we encode
// "prefer X but Y is acceptable" without giving up type safety.
type Constraint struct {
	Key      string
	Value    string
	Required bool
}

// Preference is one row of TaskSpec.SoftPreferences. Unlike constraints,
// preferences are hints only and never short-circuit workers.
type Preference struct {
	Key      string
	Value    string
	Strength float64 // [0,1]; 0 = ignore, 1 = strongly prefer
}

// FallbackPolicy enumerates the strategies Channel.Execute may take when the
// primary plan exhausts its ConvergenceBudget. Pessimistic commits an MVP
// (defined in PR-B); RuleBased defers to an env-configurable heuristic
// (defined in PR-C); Abort is the v6.0.x default and is preserved for one
// minor version.
type FallbackPolicy int

const (
	// FallbackAbort — v6.0.x default. Returns ResultKind=Failed with no
	// payload. Kept for backward compatibility during the v7.0 migration.
	FallbackAbort FallbackPolicy = iota
	// FallbackPessimistic — commit the best-effort MVP plus risk warnings
	// (defined in PR-B). The default for new TaskSpecs created by
	// NewTaskSpec.
	FallbackPessimistic
	// FallbackRuleBased — pick a candidate from an env-configurable rule
	// set (defined in PR-C). May still produce a Pass verdict.
	FallbackRuleBased
)

// String makes FallbackPolicy stable for spans, logs and tests.
func (p FallbackPolicy) String() string {
	switch p {
	case FallbackAbort:
		return "abort"
	case FallbackPessimistic:
		return "pessimistic"
	case FallbackRuleBased:
		return "rule_based"
	default:
		return fmt.Sprintf("unknown(%d)", int(p))
	}
}

// ConvergenceBudget caps how much work the planning + execution pipeline
// may do before one of the FallbackPolicies kicks in. MaxDepth caps the
// decisionplanning.Decompose recursion; MaxSteps caps the total WorkerAgent
// invocations; MaxTokens caps the projected token spend (advisory, not
// enforced here — enforcement lives in ContextBudget Phase B).
type ConvergenceBudget struct {
	MaxDepth  int
	MaxSteps  int
	MaxTokens int
	Policy    FallbackPolicy
}

// CostQuota declares the per-spec resource budget. Workers check this before
// invoking expensive tools; if the remaining quota falls below MinReserve
// the FallbackPolicy is consulted (PR-B defines the exact check).
type CostQuota struct {
	Tokens     int
	TimeMillis int
	Steps      int
	// MinReserve is the floor below which FallbackPolicy is consulted. Zero
	// disables the check (effectively always allow).
	MinReserve int
}

// TaskSpec is the unified down-link contract. Every Plan / Channel /
// WorkItem creation point MUST construct a TaskSpec via NewTaskSpec (or one
// of the With* builders) so that all three creation paths agree on field
// names and types.
//
// TaskSpec is immutable. With* methods return shallow copies; the receiver
// is never modified. This lets multiple goroutines share a base spec while
// building their own derived values without locking.
type TaskSpec struct {
	// Goal is the human-readable user intent. Required.
	Goal string

	// HardConstraints are non-negotiable. Violations short-circuit workers.
	HardConstraints []Constraint

	// SoftPreferences are hints. Violations produce warnings only.
	SoftPreferences []Preference

	// ConvergenceBudget caps recursion depth / steps / projected tokens
	// before FallbackPolicy kicks in.
	ConvergenceBudget ConvergenceBudget

	// TraceID correlates this spec to its TaskReport, ChildDownlink, audit
	// logs and SkillMemory assets. Auto-generated by NewTaskSpec.
	TraceID string

	// CostBudget declares the resource budget. Workers consult this before
	// expensive operations.
	CostBudget CostQuota

	// CreatedAt is recorded at construction. Used by the audit pipeline and
	// by tests that want to assert ordering.
	CreatedAt time.Time
}

// NewTaskSpec constructs a TaskSpec with the supplied goal. TraceID is
// auto-generated ("ts_<8 hex chars>") and CreatedAt is stamped with the
// current wall-clock time. Returns ErrTaskSpecGoalEmpty if goal is empty,
// or ErrTaskSpecTraceIDEmpty if the random source fails (effectively
// unreachable but kept for defense in depth).
func NewTaskSpec(goal string) (*TaskSpec, error) {
	if strings.TrimSpace(goal) == "" {
		return nil, NewTaskSpecGoalEmptyError()
	}
	traceID, err := newTraceID()
	if err != nil {
		return nil, NewTaskSpecTraceIDEmptyError()
	}
	return &TaskSpec{
		Goal:              goal,
		HardConstraints:   []Constraint{}, // non-nil empty slice; With* can append safely
		SoftPreferences:   []Preference{},
		ConvergenceBudget: ConvergenceBudget{Policy: FallbackPessimistic},
		TraceID:           traceID,
		CostBudget:        CostQuota{},
		CreatedAt:         time.Now(),
	}, nil
}

// newTraceID returns "ts_<8 hex chars>" drawn from crypto/rand. crypto/rand
// is used (not math/rand) so the TraceID is unpredictable across sessions,
// which matters for audit-log tamper resistance.
func newTraceID() (string, error) {
	var buf [traceIDEntropyBytes]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return TraceIDPrefix + hex.EncodeToString(buf[:]), nil
}

// WithConstraint returns a shallow copy of s with one Constraint appended.
// The receiver is not modified.
func (s *TaskSpec) WithConstraint(key, value string, required bool) *TaskSpec {
	c := *s
	// Append a fresh slice so callers can't mutate s.HardConstraints via
	// the returned pointer. Copy-on-write keeps the With* chain cheap.
	hard := make([]Constraint, len(s.HardConstraints)+1)
	copy(hard, s.HardConstraints)
	hard[len(s.HardConstraints)] = Constraint{Key: key, Value: value, Required: required}
	c.HardConstraints = hard
	return &c
}

// WithPreference returns a shallow copy of s with one Preference appended.
func (s *TaskSpec) WithPreference(key, value string, strength float64) *TaskSpec {
	c := *s
	soft := make([]Preference, len(s.SoftPreferences)+1)
	copy(soft, s.SoftPreferences)
	soft[len(s.SoftPreferences)] = Preference{Key: key, Value: value, Strength: strength}
	c.SoftPreferences = soft
	return &c
}

// WithConvergenceBudget returns a shallow copy with the supplied budget.
func (s *TaskSpec) WithConvergenceBudget(b ConvergenceBudget) *TaskSpec {
	c := *s
	c.ConvergenceBudget = b
	return &c
}

// WithTraceID returns a shallow copy with the supplied TraceID. Normally
// callers don't need this — NewTaskSpec auto-generates — but it is useful
// when re-issuing a spec with a parent TraceID for cross-layer correlation.
func (s *TaskSpec) WithTraceID(id string) *TaskSpec {
	c := *s
	c.TraceID = id
	return &c
}

// WithCostBudget returns a shallow copy with the supplied quota.
func (s *TaskSpec) WithCostBudget(q CostQuota) *TaskSpec {
	c := *s
	c.CostBudget = q
	return &c
}

// Validate enforces the invariants NewTaskSpec already established. It is
// cheap and idempotent; callers can call it any time they receive a TaskSpec
// from an untrusted source (e.g. an external queue).
func (s *TaskSpec) Validate() error {
	if s == nil {
		return NewTaskSpecGoalEmptyError()
	}
	if strings.TrimSpace(s.Goal) == "" {
		return NewTaskSpecGoalEmptyError()
	}
	if strings.TrimSpace(s.TraceID) == "" {
		return NewTaskSpecTraceIDEmptyError()
	}
	return nil
}

// DissentMaxEntries caps how many DissentEntry rows AppendDissent will
// accept. Beyond this the call is a no-op (and returns the receiver
// unchanged). 3 is the PR-A default; PR-C exposes an env flag so operators
// can tune without recompiling.
const DissentMaxEntries = 3

// DissentEntry is one minority-plan record captured on TaskReport.Dissent.
// The fields map 1:1 to SkillMemory.SOP storage so the Learn node can write
// the entry verbatim. Summary is a hash of the candidate content so we can
// dedup identical minority plans across sessions without re-uploading the
// raw text (PR-A stores the summary; the full content is captured by the
// caller before AppendDissent is invoked).
type DissentEntry struct {
	Source    string    // identifier of the minority plan (e.g. "scenario-B")
	Decision  string    // the decision the minority plan would have taken
	Reason    string    // why the plan was rejected — required for SkillMemory.SOP lookup
	Summary   string    // hex hash of the candidate content; used for cross-session dedup
	Timestamp time.Time // when the minority plan was rejected
}